#n_samples_KuaiRec

num_runs : 100
num_data_list : [500,1000,2000,4000]


n_unique_action : 10
n_train : 1500
n_optimize : 30
random_state : 12345
eps : 0.1
beta : -0.5 #pi_b softmax 
n_users : 300
bias_noise_std_s : 1.0
bias_noise_std_m : 3.0
bias_noise_std_l : 5.0