#main_kth_order

num_runs : 100
num_data : 2000
num_unique_action : 6
kth_order_list : [0,1,2,3,4,5,6]

dim_context : 5

reward_type : "continuous"
random_state : 12345
interaction_factor : 1.0

n_rounds_train_bandit_data : 5000 #5000
n_rounds_test_bandit_data : 10000 #100000

reward_std : 3.0
beta : -0.5
lambda_ : 0.8
true_element : [0,1,2]
eps : 0.2
n_users : 200