#main_n_samples_slate2

num_runs : 100
num_data_list : [500,1000,2000,4000,8000]

n_unique_action : 3
slate_size : 6
dim_context : 5

reward_type : "continuous"
random_state : 12345
interaction_factor : 5.0

n_rounds_test_bandit_data : 10000 #100000
reward_std : 3.0
beta : -0.05
eps : 0.2
n_users : 200
n_slate_abstraction : 500
# n_optimize : 30

bias_noise_std : 2.5