#main_lambda

num_runs : 100
num_data : 2000
n_unique_action : 8
lambda_list  : [0, 0.2, 0.4, 0.6, 0.8, 1.0]

dim_context : 5
#base_reward_function : linear_reward_function
#behavior_policy_function : linear_behavior_policy
reward_type : "continuous"
random_state : 12345
interaction_factor : 1.0

n_rounds_test_bandit_data : 10000 #100000

reward_std : 3.0
bias_noise_std : 2.5
#beta : -0.3
delta : 0.1
true_element : [0,1,2]
eps : 0.2
n_users : 200
n_optimize : 30