#main_bias_noise

num_runs : 100
num_data  : 2000

n_unique_action : 8
dim_context : 5
#base_reward_function : linear_reward_function
#behavior_policy_function : linear_behavior_policy
reward_type : "continuous"
random_state : 12345
interaction_factor : 1.0

n_rounds_test_bandit_data : 10000 #100000
reward_std : 3.0
beta : -0.5
lambda_ : 0.8
delta : 0.1
true_element : [0,1,2]
eps : 0.2
n_users : 200
n_optimize : 30

bias_noise_std_list : [0.0,1.0,2.0,3.0,4.0,5.0]