#main_slate_size

num_runs : 100
num_data : 1000
slate_size_list  : [4,5,6,7]
n_unique_action : 3

dim_context : 5

reward_type : "continuous"
random_state : 12345
interaction_factor : 5.0

n_rounds_test_bandit_data : 10000 #100000

reward_std : 3.0
beta : -0.1
eps : 0.2
n_users : 200
n_slate_abstraction : 30
# n_optimize : 30
bias_noise_std : 2.5